# Generated by Django 5.0.6 on 2024-05-18 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prep_time', models.DurationField(blank=True, null=True)),
                ('cook_time', models.DurationField(blank=True, null=True)),
                ('servings', models.IntegerField()),
                ('instructions', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetype')),
            ],
        ),
    ]
